# Generated by Django 4.2.1 on 2023-06-24 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 24, 11, 28, 29, 566441))),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
