# Generated by Django 4.2.1 on 2023-06-24 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usersignup_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2023, 6, 24, 11, 45, 37, 407557)),
        ),
    ]
